baseURL = "https://josephcamarena.github.io/"
languageCode = "en-us"
title = "Joe C."
theme = "cleanwhite"
paginate = 2 #frontpage pagination
publishDir = "public"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[params]
  # HTML Header settings
  header_image = "images/cybersecurity-banner-scaled.jpeg"
  title = "Topics in Cyber Security"
  slogan = "Grad School Projects, Pen Testing, and CTFs"
  SEOTitle = "Joseph Camarena Topics in Cyber Security"
  keyword = "Joseph, Camarena, Cyber, Security, CTF, CTFs, Graduate, School, Capture, The, Flag"
  AuthorName = "Joseph Camarena"
  description = "Thoughts and examples on Cyber Security, including Capture The Flags and Graduate School Projects"
  toc = true

  # Sidebar settings
  sidebar_about_description = "Joseph C. - Graduate Student, Exercise & Sports Enthusiast, and soon-to-be Hacker"
  sidebar_avatar = "images/Joe.jpg"
  about_me = true

  featured_tags = true
  featured_condition_size = 1 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."
  omit_categories = false

  friends = false
  bookmarks = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = false
  email          = "pwnerbear@pm.me"
  linkedin       = "https://www.linkedin.com/in/josephcamarena"
  github         = "https://github.com/JosephCamarena"
